# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:04:53+00:00

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, RootModel


class CloseoutDocument(RootModel[str]):
    root: str = Field(
        ...,
        description='Represents a file hyperlink or external hyperlink to a project closeout final report artifact.',
    )


class CoInvestigator(RootModel[str]):
    root: str = Field(
        ...,
        description='The name of an investigator who is a scientist or engineer for an project.',
    )


class Destination(RootModel[str]):
    root: str = Field(
        ...,
        description='Represents a destination towards which the technology on this project helps advance the Agency goals.',
    )


class File(BaseModel):
    id: Optional[int] = Field(None, description='Unique identifier for the file.')
    size: Optional[str] = Field(None, description='The size of the file in bytes.')
    url: Optional[str] = Field(
        None,
        description='The TechPort URL at which the file is accessible for download.',
    )


class LibraryItem(BaseModel):
    completionDate: Optional[str] = Field(
        None, description='Date the library item was completed.'
    )
    description: Optional[str] = Field(
        None, description='Description of the library item.'
    )
    externalUrl: Optional[str] = Field(
        None, description='External URL for the library item.'
    )
    files: Optional[List[File]] = Field(
        None, description='List of files associated with the library item.'
    )
    id: Optional[int] = Field(
        None, description='Unique identifier for the library item.'
    )
    publishedBy: Optional[str] = Field(
        None, description='Publisher of the library item.'
    )
    publishedDate: Optional[str] = Field(
        None, description='Date the library item was published.'
    )
    title: Optional[str] = Field(None, description='Title of the library item')
    type: Optional[str] = Field(
        None, description='Identifies the type of library item, e.g. Image'
    )


class Organization(BaseModel):
    acronym: Optional[str] = Field(None, description='The acronym of the organization.')
    city: Optional[str] = Field(
        None, description='The city in which the organization is located.'
    )
    name: Optional[str] = Field(None, description='The name of the organization.')
    state: Optional[str] = Field(
        None, description='The state in which the organization is located.'
    )


class PrincipalInvestigator(RootModel[str]):
    root: str = Field(
        ...,
        description='The name of the Principal Investigator who is a lead scientist or engineer for an project.',
    )


class ProgramDirector(RootModel[str]):
    root: str = Field(
        ...,
        description='The name of a Program Director responsible for management of an project.',
    )


class ProgramManager(RootModel[str]):
    root: str = Field(
        ...,
        description='The name of a Program Manager responsible for management of an project.',
    )


class ProjectManager(RootModel[str]):
    root: str = Field(
        ...,
        description='The name of a Project Manager responsible for management of an project.',
    )


class TechnologyArea(BaseModel):
    code: Optional[str] = Field(
        None, description='The code identifier for the Technology Area.'
    )
    id: Optional[int] = Field(
        None, description='Unique identifier for the Technology Area.'
    )
    name: Optional[str] = Field(None, description='The name of the Technology Area.')


class WorkLocation(RootModel[str]):
    root: str = Field(
        ..., description='A state/territory where work on this project is performed.'
    )


class Format(Enum):
    json = 'json'
    xml = 'xml'


class Project(BaseModel):
    acronym: Optional[str] = Field(None, description='Abbreviated name of the project.')
    additionalTas: Optional[List[TechnologyArea]] = Field(
        None,
        description='List of additional and cross-cutting technology areas associated with the project.',
    )
    benefits: Optional[str] = Field(
        None,
        description='Describes the benefits offered to NASA funded and planned missions, unfunded or planned missions, commercial space industry, and to the nation.',
    )
    closeoutDocuments: Optional[List[CloseoutDocument]] = Field(
        None,
        description='List of document files or links to the project final report closeout documentation.',
    )
    closeoutSummary: Optional[str] = Field(
        None, description='The project closeout summary excerpt.'
    )
    coFundingPartners: Optional[List[Organization]] = Field(
        None,
        description='Other government agencies, NASA Mission Directoratres, universities, or commercial entities performing contributing resources to this project.',
    )
    coInvestigators: Optional[List[CoInvestigator]] = Field(
        None,
        description='Names of the additional investigators who are scientists or engineers for this project.',
    )
    description: Optional[str] = Field(
        None, description='A detailed description of the project.'
    )
    destinations: Optional[List[Destination]] = Field(
        None,
        description='List of the NASA destinations the technology on this project helps achieve.',
    )
    endDate: Optional[str] = Field(
        None,
        description='The month and year the project is expected to complete its work.',
    )
    id: Optional[int] = Field(None, description='Unique identifier for the project.')
    lastUpdated: Optional[date] = Field(
        None,
        description='ISO 8601 full-date in the format YYYY-MM-DD describing the last time this project was updated.',
    )
    leadOrganization: Optional[Organization] = None
    libraryItems: Optional[List[LibraryItem]] = Field(
        None, description='List of library items in the project library.'
    )
    primaryTas: Optional[List[TechnologyArea]] = Field(
        None,
        description='List of primary technolgy areas (from the NASA Technology Roadmap) associated with the project.',
    )
    principalInvestigators: Optional[List[PrincipalInvestigator]] = Field(
        None,
        description='Names of the Principal Investigators who are the lead scientists or engineers for this project.',
    )
    programDirectors: Optional[List[ProgramDirector]] = Field(
        None,
        description='Names of the Program Directors responsible for the management of this project.',
    )
    programManagers: Optional[List[ProgramManager]] = Field(
        None,
        description='Names of the Program Managers responsible for the management of this project.',
    )
    projectManagers: Optional[List[ProjectManager]] = Field(
        None,
        description='Names of the Project Managers responsible for the management of this project.',
    )
    responsibleMissionDirectorateOrOffice: Optional[str] = Field(
        None,
        description='The NASA Mission Directorate or Office that is the primary funding source for this project.',
    )
    responsibleProgram: Optional[str] = Field(
        None,
        description='The NASA program that is the primary funding source for this project.',
    )
    startDate: Optional[str] = Field(
        None, description='The month and year the project was authorized to proceed.'
    )
    status: Optional[str] = Field(
        None,
        description='Indicates whether the project is currently active, completed, or canceled.',
    )
    supportedMissionType: Optional[str] = Field(
        None,
        description='The supported mission type (Projected Mission, Planned Mission, or Pull).',
    )
    supportingOrganizations: Optional[List[Organization]] = Field(
        None,
        description='The supporting organizations for this project that are conducting work on the project.',
    )
    technologyMaturityCurrent: Optional[str] = Field(
        None,
        description='The current technology maturity (technology readiness level) of the project.',
    )
    technologyMaturityEnd: Optional[str] = Field(
        None,
        description='The estimated technology maturity (technology readiness level) of the project at its end.',
    )
    technologyMaturityStart: Optional[str] = Field(
        None,
        description='The technology maturity (technology readiness level) of the project at its beginning.',
    )
    title: Optional[str] = Field(None, description='Title of the project.')
    website: Optional[str] = Field(
        None, description='The URL for the associated website.'
    )
    workLocations: Optional[List[WorkLocation]] = Field(
        None,
        description='States and territories with people performing work on this project.',
    )
