# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:04:53+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class FormatGetResponse(BaseModel):
    id: Optional[int] = None
    lastUpdated: Optional[str] = None
