# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:04:53+00:00



import argparse
import json
import os
from datetime import date
from typing import *

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity
from fastapi import Path, Query

from models import Format, Project
from models.ApiProjects_ import FormatGetResponse

app = MCPProxy(
    contact={
        'email': 'hq-techport@mail.nasa.gov',
        'name': 'TechPort Team',
        'url': 'https://techport.nasa.gov',
    },
    description='TechPort RESTful API',
    title='TechPort',
    version='3.4.0',
    servers=[
        {'url': 'http://techport.nasa.gov/api'},
        {'url': 'https://techport.nasa.gov/api'},
    ],
)


@app.get(
    '/api',
    description=""" Returns the swagger specification for the API. """,
    tags=['api_request_handling'],
)
def get_api():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/projects/{id}{.format}',
    description=""" Returns information about a specific technology project. """,
    tags=['api_request_handling'],
)
def get_api_projects__id__format(
    id: int, format: Format = 'xml', field_format: str = Path(..., alias='.format')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/projects{.format}',
    description=""" Returns a list of available technology project IDs. """,
    tags=['api_request_handling'],
)
def get_api_projects__format(
    updated_since: date = Query(..., alias='updatedSince'),
    format: Format = 'json',
    field_format: str = Path(..., alias='.format'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
